apiVersion: batch/v1
kind: Job
metadata:
  name: cloudfront-invalidate-cache
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      containers:
        - name: cloudfront-cache
          image: amazon/aws-cli:2.27.10
          command: ["/bin/sh", "-c"]
          args: 
            - >
              aws cloudfront create-invalidation
                --distribution-id {{ .Values.cloudfront.distributionId }}
                --paths "{{ .Values.cloudfront.invalidationPaths }}"
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: secret_access_key
          - name: AWS_REGION
            value: "{{ .Values.cloudfront.region }}"
      restartPolicy: Never
  backoffLimit: 1