# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "helm-react-ingress"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - host: "helm-react.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "helm-react-service"
                port:
                  number: 80
