apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: {{ .Values.appName }}
  labels: 
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: flask
  selector: 
    app: {{ .Values.appName }}
    tier: frontend
  type: LoadBalancer